[project]
name = "pdfxtmd"
version = "2.0.0"
description = "Python bindings for PDFxTMDLib: collinear PDFs, TMDs, and double parton distributions (DPDs)."
authors = [
    {name = "Ramin Kord Valeshabadi", email = "raminkord92@gmail.com"}
]
license = {text = "GPL-3.0"}
readme = "examples/python/readme-pyversion.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Raminkord92/PDFxTMD"

[build-system]
requires = ["setuptools", "wheel", "pybind11", "cmake>=3.15"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = "pp37* pp*"
manylinux-x86_64-image = "manylinux_2_28"
